services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: quiz_app_backend
    restart: unless-stopped
    env_file:
      - ./Backend/.env
    environment:
      - NODE_ENV=production
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./Backend:/app
      - /app/node_modules
    networks:
      - quizz_app_network
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: quiz_app_postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quizz_app_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  quizz_app_network: